# Numpy - Numerical Python
- It is similar to a list or tuple


### Advantages of Numpy array over list:
1. Allows many mathematical operations
2. Faster operations

In [ ]:
import numpy as np

# List vs Numpy time taken

In [ ]:
from time import process_time

## Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
list_time = end_time - start_time
print(f"Operation time on python_list = {list_time}")


Operation time on python_list = 0.0008912209999998311


## Time taken by a numpy array

In [ ]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5 # adding 5 to all elements in the array
end_time = process_time()
np_time = end_time - start_time
print(f"Operation time on numpy_array = {np_time}")

Operation time on numpy_array = 0.00037399100000001795


In [ ]:
# Comparing times
if list_time > np_time:
  print("np is faster")
else:
  print("list is faster")

np is faster


# Numpy arrays


In [ ]:
# list
li_1 = [1,2,3,4]
print(li_1) # [1,2,3,4] comma separated
print(type(li_1)) #list

#numpy array
np_arr = np.array([1,2,3])
print(np_arr) # [1 2 3] not comma separated
print(type(np_arr)) # numpy.ndarray -> n dimensional array



[1, 2, 3, 4]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 1 dimensional array
one_dim = np.array([10, 20, 30, 40])
print(one_dim)
print(one_dim.shape) # in 1D shape gives no of column
print()

# 2 dimensional array
two_dim = np.array([(5,10,15),(2,4,6)])
print(two_dim)
print(two_dim.shape) # in nD shape gives (row,col)
print()

#note: When you do not mention any dtype, default is integers

#creating a array of floating points
float_arr = np.array([(1,2,3),(2,3,2)],dtype = float)
print(float_arr)
print(float_arr.shape)
print()

[10 20 30 40]
(4,)

[[ 5 10 15]
 [ 2  4  6]]
(2, 3)

[[1. 2. 3.]
 [2. 3. 2.]]
(2, 3)



# Initial placeholders in array

In [ ]:
# array of all values zero -> syntax: np.zeros((row,col))
zero_arr = np.zeros((4,5))
print(zero_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# array of all values ones -> syntax: np.ones((row,col))
one_arr = np.ones((4,5))
print(one_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# array of a particular value -> syntax: np.full((row,col),value)
n_arr = np.full((4,5),5)
print(n_arr)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
# Identity Matrix -> Syntax: np.eye((n)) here n is the shape as nxn
identity = np.eye((4))
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# array of random values -> syntax: np.random.random((row,col)), here all values will be btw 0 and 1
random_matrix = np.random.random((2,2))
print(random_matrix)

[[0.56380884 0.82947062]
 [0.97947413 0.7721329 ]]


In [ ]:
# array of random "int" values within specific range-> syntax: np.random.randint(start_range,end_range,(row,col)), here all values will be btw 0 and 1
randint_matrix = np.random.randint(10,100,(2,2))
print(randint_matrix)

[[55 66]
 [15 71]]


# Evenly spaced array
1. specifying the no of values req
  - keyword: np.linspace(start,end,no of values)
2. specifying the step
  - keyword: np.arange(start,end,step)

In [ ]:
# specifying the values
value_specified = np.linspace(10,30,4)
print(value_specified)

#specifying step
step_specified = np.arange(10,30,5)
print(step_specified)

[10.         16.66666667 23.33333333 30.        ]
[10 15 20 25]


# converting a list/tuple to numpy array
- keyword: np.asarray(list_name/tuple_name)


In [ ]:
list_arr = [1,1,2,3]
np_list_arr = np.asarray(list_arr)
print(np_list_arr)
print(type(np_list_arr))

[1 1 2 3]
<class 'numpy.ndarray'>


# Analysing a numpy array
- finding shape -> arr.shape
- finding dimension -> arr.ndim
- finding size -> arr.size
- finding data type of elements in array = arr.dtype

In [ ]:
arr = np.random.randint(10,100,(3,4))
print(arr)
print(f"\nShape of array = {arr.shape}")
print(f"\nNo of dimensions = {arr.ndim}")
print(f"\nSize of arr = {arr.size}")
print(f"\ndata type = {arr.dtype}")

[[36 78 33 48]
 [84 27 47 58]
 [19 10 96 24]]

Shape of array = (3, 4)

No of dimensions = 2

Size of arr = 12

data type = int64


# Operations on array

In [ ]:
a = np.random.randint(1,5,(2,2))
b = np.random.randint(1,5,(2,2))
print(a)
print()
print(b)

[[3 4]
 [2 4]]

[[2 4]
 [2 1]]


In [55]:
print(a+b) # can also use np.add(a,b)
print()
print(a-b) # can also use np.subtract(a,b)
print()
print(a*b) # can also use np.product(a,b)
print()
print(a/b) # can also use np.divide(a,b)


[[5 8]
 [4 5]]

[[1 0]
 [0 3]]

[[ 6 16]
 [ 4  4]]

[[1.5 1. ]
 [1.  4. ]]


# Array manipulations

In [56]:
arr1 = np.random.randint(10,20,(3,2))
print(arr1)
print(arr1.shape)
print()


[[10 16]
 [19 12]
 [13 19]]
(3, 2)



# Transpose
- np.transpose()
- arr.T

In [57]:
arr_t = np.transpose(arr1)
print(arr_t)
print(arr_t.shape)

[[10 19 13]
 [16 12 19]]
(2, 3)


In [58]:
arr_t2 = arr1.T
print(arr_t2)
print(arr_t2.shape)

[[10 19 13]
 [16 12 19]]
(2, 3)


# reshape
- arr.reshape((row,col))

In [60]:
print(arr1)
arr2 = arr1.reshape((2,3))
print()
print(arr2)

[[10 16]
 [19 12]
 [13 19]]

[[10 16 19]
 [12 13 19]]
